apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "qwen-llm-dotjson"
  namespace: kserve-test
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface-dotjson
      args:
        - --model_name=qwen
        - --gpu_memory_utilization=0.9
        - --structured-outputs-config.backend=dotjson
        - --structured-outputs-config.disable-fallback=true
        - --structured-outputs-config.disable-any-whitespace=false
        - --structured-outputs-config.disable-additional-properties=false
      runtime: kserve-huggingfaceserver-dotjson
      storageUri: "hf://Qwen/Qwen3-0.6B"
      resources:
        limits:
          cpu: "2"
          memory: 6Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
